export const DEMO_DATA = {
  "mines": [
    {
      "name": "Jharia Eastern Colliery",
      "mineId": "COL-E001",
      "subsidiary": "BCCL",
      "state": "Jharkhand",
      "district": "Dhanbad",
      "latitude": 23.7509,
      "longitude": 86.4148,
      "mineType": "Underground",
      "productionCapacity": 5000000,
      "currentProduction": 3800000,
      "status": "ACTIVE",
      "riskScore": 87,
      "riskLevel": "CRITICAL",
      "openViolations": 12,
      "overdueActions": 6,
      "compliancePercentage": 54,
      "_id": "mine-1",
      "createdAt": -2592000000
    },
    {
      "name": "Raniganj North Block",
      "mineId": "COL-R002",
      "subsidiary": "ECL",
      "state": "West Bengal",
      "district": "Paschim Bardhaman",
      "latitude": 23.6167,
      "longitude": 87.1333,
      "mineType": "Open Cast",
      "productionCapacity": 8000000,
      "currentProduction": 6200000,
      "status": "ACTIVE",
      "riskScore": 78,
      "riskLevel": "HIGH",
      "openViolations": 8,
      "overdueActions": 4,
      "compliancePercentage": 62,
      "_id": "mine-2",
      "createdAt": -2592000000
    },
    {
      "name": "Singrauli Mega Project",
      "mineId": "COL-S003",
      "subsidiary": "Northern Coalfields",
      "state": "Madhya Pradesh",
      "district": "Singrauli",
      "latitude": 24.1944,
      "longitude": 82.6781,
      "mineType": "Open Cast",
      "productionCapacity": 12000000,
      "currentProduction": 10500000,
      "status": "ACTIVE",
      "riskScore": 72,
      "riskLevel": "HIGH",
      "openViolations": 6,
      "overdueActions": 3,
      "compliancePercentage": 68,
      "_id": "mine-3",
      "createdAt": -2592000000
    },
    {
      "name": "Talcher West Pit",
      "mineId": "COL-T004",
      "subsidiary": "MCL",
      "state": "Odisha",
      "district": "Angul",
      "latitude": 20.9517,
      "longitude": 85.2336,
      "mineType": "Open Cast",
      "productionCapacity": 10000000,
      "currentProduction": 8200000,
      "status": "ACTIVE",
      "riskScore": 55,
      "riskLevel": "MEDIUM",
      "openViolations": 4,
      "overdueActions": 2,
      "compliancePercentage": 74,
      "_id": "mine-4",
      "createdAt": -2592000000
    },
    {
      "name": "Korba Coal Mine",
      "mineId": "COL-K005",
      "subsidiary": "SECL",
      "state": "Chhattisgarh",
      "district": "Korba",
      "latitude": 22.3595,
      "longitude": 82.6847,
      "mineType": "Underground",
      "productionCapacity": 6000000,
      "currentProduction": 4800000,
      "status": "ACTIVE",
      "riskScore": 45,
      "riskLevel": "MEDIUM",
      "openViolations": 3,
      "overdueActions": 1,
      "compliancePercentage": 78,
      "_id": "mine-5",
      "createdAt": -2592000000
    },
    {
      "name": "Dhanbad Incline Mine",
      "mineId": "COL-D006",
      "subsidiary": "BCCL",
      "state": "Jharkhand",
      "district": "Dhanbad",
      "latitude": 23.7957,
      "longitude": 86.4304,
      "mineType": "Underground",
      "productionCapacity": 3000000,
      "currentProduction": 2400000,
      "status": "ACTIVE",
      "riskScore": 62,
      "riskLevel": "HIGH",
      "openViolations": 5,
      "overdueActions": 3,
      "compliancePercentage": 70,
      "_id": "mine-6",
      "createdAt": -2592000000
    },
    {
      "name": "Godavari Mega Project",
      "mineId": "COL-G007",
      "subsidiary": "Singareni Collieries",
      "state": "Telangana",
      "district": "Mancherial",
      "latitude": 18.8679,
      "longitude": 79.4612,
      "mineType": "Open Cast",
      "productionCapacity": 9000000,
      "currentProduction": 7500000,
      "status": "ACTIVE",
      "riskScore": 28,
      "riskLevel": "LOW",
      "openViolations": 1,
      "overdueActions": 0,
      "compliancePercentage": 88,
      "_id": "mine-7",
      "createdAt": -2592000000
    },
    {
      "name": "Lohit River Basin",
      "mineId": "COL-L008",
      "subsidiary": "NEIC",
      "state": "Assam",
      "district": "Lakhimpur",
      "latitude": 27.2353,
      "longitude": 94.1011,
      "mineType": "Underground",
      "productionCapacity": 2000000,
      "currentProduction": 1200000,
      "status": "ACTIVE",
      "riskScore": 35,
      "riskLevel": "MEDIUM",
      "openViolations": 2,
      "overdueActions": 1,
      "compliancePercentage": 82,
      "_id": "mine-8",
      "createdAt": -2592000000
    },
    {
      "name": "Neyveli Expansion Block",
      "mineId": "COL-N009",
      "subsidiary": "NLC India",
      "state": "Tamil Nadu",
      "district": "Cuddalore",
      "latitude": 11.6234,
      "longitude": 79.4922,
      "mineType": "Open Cast",
      "productionCapacity": 7000000,
      "currentProduction": 5800000,
      "status": "ACTIVE",
      "riskScore": 18,
      "riskLevel": "LOW",
      "openViolations": 0,
      "overdueActions": 0,
      "compliancePercentage": 94,
      "_id": "mine-9",
      "createdAt": -2592000000
    },
    {
      "name": "Mand-Raigarh Block",
      "mineId": "COL-M010",
      "subsidiary": "SECL",
      "state": "Chhattisgarh",
      "district": "Raigarh",
      "latitude": 21.8958,
      "longitude": 83.3963,
      "mineType": "Underground",
      "productionCapacity": 4500000,
      "currentProduction": 3200000,
      "status": "ACTIVE",
      "riskScore": 42,
      "riskLevel": "MEDIUM",
      "openViolations": 3,
      "overdueActions": 2,
      "compliancePercentage": 76,
      "_id": "mine-10",
      "createdAt": -2592000000
    },
    {
      "name": "Patratu Thermal Colliery",
      "mineId": "COL-P011",
      "subsidiary": "CCL",
      "state": "Jharkhand",
      "district": "Ramgarh",
      "latitude": 23.6667,
      "longitude": 85.3667,
      "mineType": "Underground",
      "productionCapacity": 3500000,
      "currentProduction": 2800000,
      "status": "UNDER_REVIEW",
      "riskScore": 58,
      "riskLevel": "MEDIUM",
      "openViolations": 4,
      "overdueActions": 2,
      "compliancePercentage": 72,
      "_id": "mine-11",
      "createdAt": -2592000000
    },
    {
      "name": "Amadubi Open Pit",
      "mineId": "COL-A012",
      "subsidiary": "BCCL",
      "state": "Jharkhand",
      "district": "East Singhbhum",
      "latitude": 22.8504,
      "longitude": 86.2254,
      "mineType": "Open Cast",
      "productionCapacity": 4000000,
      "currentProduction": 3100000,
      "status": "ACTIVE",
      "riskScore": 8,
      "riskLevel": "LOW",
      "openViolations": 0,
      "overdueActions": 0,
      "compliancePercentage": 96,
      "_id": "mine-12",
      "createdAt": -2592000000
    }
  ],
  "compliance": [
    {
      "title": "Gas monitoring system upgrade",
      "category": "Safety",
      "priority": "CRITICAL",
      "status": "OVERDUE",
      "dueDate": -18652800000,
      "mineId": "mine-1",
      "_id": "comp-1",
      "description": "Gas monitoring system upgrade \u2014 statutory requirement for safety compliance.",
      "severity": "CRITICAL",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Fire safety equipment inspection",
      "category": "Safety",
      "priority": "HIGH",
      "status": "OVERDUE",
      "dueDate": -18480000000,
      "mineId": "mine-1",
      "_id": "comp-2",
      "description": "Fire safety equipment inspection \u2014 statutory requirement for safety compliance.",
      "severity": "HIGH",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Water discharge compliance report",
      "category": "Environment",
      "priority": "HIGH",
      "status": "PENDING",
      "dueDate": -17788800000,
      "mineId": "mine-1",
      "_id": "comp-3",
      "description": "Water discharge compliance report \u2014 statutory requirement for environment compliance.",
      "severity": "HIGH",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Worker safety training certification",
      "category": "Labour",
      "priority": "MEDIUM",
      "status": "IN_PROGRESS",
      "dueDate": -17356800000,
      "mineId": "mine-1",
      "_id": "comp-4",
      "description": "Worker safety training certification \u2014 statutory requirement for labour compliance.",
      "severity": "MEDIUM",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Monthly production report submission",
      "category": "Production",
      "priority": "HIGH",
      "status": "OVERDUE",
      "dueDate": -18393600000,
      "mineId": "mine-1",
      "_id": "comp-5",
      "description": "Monthly production report submission \u2014 statutory requirement for production compliance.",
      "severity": "HIGH",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Annual mining license renewal",
      "category": "Regulatory",
      "priority": "CRITICAL",
      "status": "PENDING",
      "dueDate": -16924800000,
      "mineId": "mine-1",
      "_id": "comp-6",
      "description": "Annual mining license renewal \u2014 statutory requirement for regulatory compliance.",
      "severity": "CRITICAL",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Dust suppression system check",
      "category": "Safety",
      "priority": "HIGH",
      "status": "IN_PROGRESS",
      "dueDate": -17961600000,
      "mineId": "mine-2",
      "_id": "comp-7",
      "description": "Dust suppression system check \u2014 statutory requirement for safety compliance.",
      "severity": "HIGH",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Environmental impact assessment",
      "category": "Environment",
      "priority": "CRITICAL",
      "status": "OVERDUE",
      "dueDate": -18825600000,
      "mineId": "mine-2",
      "_id": "comp-8",
      "description": "Environmental impact assessment \u2014 statutory requirement for environment compliance.",
      "severity": "CRITICAL",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Contractor safety audit",
      "category": "Labour",
      "priority": "MEDIUM",
      "status": "PENDING",
      "dueDate": -17529600000,
      "mineId": "mine-2",
      "_id": "comp-9",
      "description": "Contractor safety audit \u2014 statutory requirement for labour compliance.",
      "severity": "MEDIUM",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Blasting protocol review",
      "category": "Safety",
      "priority": "HIGH",
      "status": "OVERDUE",
      "dueDate": -18307200000,
      "mineId": "mine-2",
      "_id": "comp-10",
      "description": "Blasting protocol review \u2014 statutory requirement for safety compliance.",
      "severity": "HIGH",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Haul road maintenance",
      "category": "Production",
      "priority": "MEDIUM",
      "status": "IN_PROGRESS",
      "dueDate": -17184000000,
      "mineId": "mine-3",
      "_id": "comp-11",
      "description": "Haul road maintenance \u2014 statutory requirement for production compliance.",
      "severity": "MEDIUM",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Ground water monitoring",
      "category": "Environment",
      "priority": "HIGH",
      "status": "OVERDUE",
      "dueDate": -18566400000,
      "mineId": "mine-3",
      "_id": "comp-12",
      "description": "Ground water monitoring \u2014 statutory requirement for environment compliance.",
      "severity": "HIGH",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "PPE compliance audit",
      "category": "Labour",
      "priority": "HIGH",
      "status": "PENDING",
      "dueDate": -17702400000,
      "mineId": "mine-3",
      "_id": "comp-13",
      "description": "PPE compliance audit \u2014 statutory requirement for labour compliance.",
      "severity": "HIGH",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Coal washing plant emissions",
      "category": "Environment",
      "priority": "MEDIUM",
      "status": "COMPLETED",
      "dueDate": -19084800000,
      "completedAt": -19171200000,
      "mineId": "mine-4",
      "_id": "comp-14",
      "description": "Coal washing plant emissions \u2014 statutory requirement for environment compliance.",
      "severity": "MEDIUM",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Ventilation system upgrade",
      "category": "Safety",
      "priority": "HIGH",
      "status": "IN_PROGRESS",
      "dueDate": -17875200000,
      "mineId": "mine-4",
      "_id": "comp-15",
      "description": "Ventilation system upgrade \u2014 statutory requirement for safety compliance.",
      "severity": "HIGH",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Tailings dam inspection",
      "category": "Safety",
      "priority": "CRITICAL",
      "status": "COMPLETED",
      "dueDate": -19516800000,
      "completedAt": -19603200000,
      "mineId": "mine-5",
      "_id": "comp-16",
      "description": "Tailings dam inspection \u2014 statutory requirement for safety compliance.",
      "severity": "CRITICAL",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Worker health screening",
      "category": "Labour",
      "priority": "MEDIUM",
      "status": "PENDING",
      "dueDate": -16492800000,
      "mineId": "mine-5",
      "_id": "comp-17",
      "description": "Worker health screening \u2014 statutory requirement for labour compliance.",
      "severity": "MEDIUM",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Roof support reinforcement",
      "category": "Safety",
      "priority": "CRITICAL",
      "status": "OVERDUE",
      "dueDate": -18739200000,
      "mineId": "mine-6",
      "_id": "comp-18",
      "description": "Roof support reinforcement \u2014 statutory requirement for safety compliance.",
      "severity": "CRITICAL",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Methane drainage system",
      "category": "Safety",
      "priority": "HIGH",
      "status": "OVERDUE",
      "dueDate": -18393600000,
      "mineId": "mine-6",
      "_id": "comp-19",
      "description": "Methane drainage system \u2014 statutory requirement for safety compliance.",
      "severity": "HIGH",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Employment records update",
      "category": "Regulatory",
      "priority": "MEDIUM",
      "status": "IN_PROGRESS",
      "dueDate": -17616000000,
      "mineId": "mine-6",
      "_id": "comp-20",
      "description": "Employment records update \u2014 statutory requirement for regulatory compliance.",
      "severity": "MEDIUM",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Rain water harvesting setup",
      "category": "Environment",
      "priority": "LOW",
      "status": "COMPLETED",
      "dueDate": -19948800000,
      "completedAt": -20121600000,
      "mineId": "mine-7",
      "_id": "comp-21",
      "description": "Rain water harvesting setup \u2014 statutory requirement for environment compliance.",
      "severity": "LOW",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Quarterly safety drill",
      "category": "Safety",
      "priority": "MEDIUM",
      "status": "COMPLETED",
      "dueDate": -18652800000,
      "completedAt": -18739200000,
      "mineId": "mine-7",
      "_id": "comp-22",
      "description": "Quarterly safety drill \u2014 statutory requirement for safety compliance.",
      "severity": "MEDIUM",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Equipment calibration check",
      "category": "Production",
      "priority": "MEDIUM",
      "status": "PENDING",
      "dueDate": -17011200000,
      "mineId": "mine-8",
      "_id": "comp-23",
      "description": "Equipment calibration check \u2014 statutory requirement for production compliance.",
      "severity": "MEDIUM",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Emission monitoring report",
      "category": "Environment",
      "priority": "LOW",
      "status": "COMPLETED",
      "dueDate": -20812800000,
      "completedAt": -20985600000,
      "mineId": "mine-9",
      "_id": "comp-24",
      "description": "Emission monitoring report \u2014 statutory requirement for environment compliance.",
      "severity": "LOW",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Roof bolting inspection",
      "category": "Safety",
      "priority": "HIGH",
      "status": "OVERDUE",
      "dueDate": -18307200000,
      "mineId": "mine-10",
      "_id": "comp-25",
      "description": "Roof bolting inspection \u2014 statutory requirement for safety compliance.",
      "severity": "HIGH",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Emergency response plan update",
      "category": "Safety",
      "priority": "CRITICAL",
      "status": "IN_PROGRESS",
      "dueDate": -17961600000,
      "mineId": "mine-11",
      "_id": "comp-26",
      "description": "Emergency response plan update \u2014 statutory requirement for safety compliance.",
      "severity": "CRITICAL",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Noise pollution mitigation",
      "category": "Environment",
      "priority": "MEDIUM",
      "status": "PENDING",
      "dueDate": -17356800000,
      "mineId": "mine-11",
      "_id": "comp-27",
      "description": "Noise pollution mitigation \u2014 statutory requirement for environment compliance.",
      "severity": "MEDIUM",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    },
    {
      "title": "Boundary wall inspection",
      "category": "Regulatory",
      "priority": "LOW",
      "status": "COMPLETED",
      "dueDate": -20380800000,
      "completedAt": -20553600000,
      "mineId": "mine-12",
      "_id": "comp-28",
      "description": "Boundary wall inspection \u2014 statutory requirement for regulatory compliance.",
      "severity": "LOW",
      "responsibleOfficial": "Inspector Team",
      "createdAt": -2592000000,
      "updatedAt": 0
    }
  ],
  "inspections": [
    {
      "severity": "CRITICAL",
      "description": "Emergency evacuation route blocked by debris",
      "observations": "Route B-7 completely blocked. Workers in sector 3 have no safe exit.",
      "status": "OPEN",
      "_id": "inspection-1",
      "mineId": "mine-1",
      "inspectorId": "inspector-1",
      "inspectorName": "Rajesh Kumar",
      "date": -2592000000,
      "latitude": 23.7509,
      "longitude": 86.4148,
      "inspectionType": "Safety",
      "correctiveAction": "Address: Emergency evacuation route blocked by debris",
      "deadline": 1209600000,
      "createdAt": -2592000000
    },
    {
      "severity": "HIGH",
      "description": "Gas detector malfunction in main shaft",
      "observations": "3 out of 12 gas detectors not functioning. Risk of undetected gas accumulation.",
      "status": "IN_PROGRESS",
      "_id": "inspection-2",
      "mineId": "mine-1",
      "inspectorId": "inspector-2",
      "inspectorName": "Priya Sharma",
      "date": -2419200000,
      "latitude": 23.7509,
      "longitude": 86.4148,
      "inspectionType": "Safety",
      "correctiveAction": "Address: Gas detector malfunction in main shaft",
      "deadline": 1209600000,
      "createdAt": -2419200000
    },
    {
      "severity": "HIGH",
      "description": "Excessive water discharge into nearby stream",
      "observations": "pH levels measured at 3.2 \u2014 well below acceptable limits.",
      "status": "OPEN",
      "_id": "inspection-3",
      "mineId": "mine-1",
      "inspectorId": "inspector-3",
      "inspectorName": "Amit Singh",
      "date": -2246400000,
      "latitude": 23.7509,
      "longitude": 86.4148,
      "inspectionType": "Environment",
      "correctiveAction": "Address: Excessive water discharge into nearby stream",
      "deadline": 1209600000,
      "createdAt": -2246400000
    },
    {
      "severity": "MEDIUM",
      "description": "Inadequate lighting in underground section C",
      "observations": "Several work areas below minimum lux requirements.",
      "status": "IN_PROGRESS",
      "_id": "inspection-4",
      "mineId": "mine-2",
      "inspectorId": "inspector-4",
      "inspectorName": "Sunita Devi",
      "date": -2073600000,
      "latitude": 23.6167,
      "longitude": 87.1333,
      "inspectionType": "Safety",
      "correctiveAction": "Address: Inadequate lighting in underground section C",
      "deadline": 1209600000,
      "createdAt": -2073600000
    },
    {
      "severity": "HIGH",
      "description": "Dust levels exceeding PM2.5 limits",
      "observations": "Continuous monitoring shows average PM2.5 at 180 \u00b5g/m\u00b3 over past week.",
      "status": "OPEN",
      "_id": "inspection-5",
      "mineId": "mine-2",
      "inspectorId": "inspector-5",
      "inspectorName": "Vikram Patel",
      "date": -1900800000,
      "latitude": 23.6167,
      "longitude": 87.1333,
      "inspectionType": "Environment",
      "correctiveAction": "Address: Dust levels exceeding PM2.5 limits",
      "deadline": 1209600000,
      "createdAt": -1900800000
    },
    {
      "severity": "MEDIUM",
      "description": "Haul truck brake inspection overdue",
      "observations": "12 trucks past their scheduled brake inspection date.",
      "status": "IN_PROGRESS",
      "_id": "inspection-6",
      "mineId": "mine-3",
      "inspectorId": "inspector-1",
      "inspectorName": "Rajesh Kumar",
      "date": -1728000000,
      "latitude": 24.1944,
      "longitude": 82.6781,
      "inspectionType": "Equipment",
      "correctiveAction": "Address: Haul truck brake inspection overdue",
      "deadline": 1209600000,
      "createdAt": -1728000000
    },
    {
      "severity": "LOW",
      "description": "Worker safety card verification",
      "observations": "All workers verified. 3 temporary cards need renewal.",
      "status": "RESOLVED",
      "_id": "inspection-7",
      "mineId": "mine-3",
      "inspectorId": "inspector-2",
      "inspectorName": "Priya Sharma",
      "date": -1555200000,
      "latitude": 24.1944,
      "longitude": 82.6781,
      "inspectionType": "Labour",
      "correctiveAction": null,
      "deadline": null,
      "createdAt": -1555200000
    },
    {
      "severity": "MEDIUM",
      "description": "Fire extinguisher placement review",
      "observations": "Some extinguishers placed at incorrect heights.",
      "status": "RESOLVED",
      "_id": "inspection-8",
      "mineId": "mine-4",
      "inspectorId": "inspector-3",
      "inspectorName": "Amit Singh",
      "date": -1382400000,
      "latitude": 20.9517,
      "longitude": 85.2336,
      "inspectionType": "Safety",
      "correctiveAction": "Address: Fire extinguisher placement review",
      "deadline": 1209600000,
      "createdAt": -1382400000
    },
    {
      "severity": "CRITICAL",
      "description": "Roof instability detected in gallery G-4",
      "observations": "Significant cracking observed in roof strata. Immediate evacuation recommended.",
      "status": "OPEN",
      "_id": "inspection-9",
      "mineId": "mine-6",
      "inspectorId": "inspector-4",
      "inspectorName": "Sunita Devi",
      "date": -1209600000,
      "latitude": 23.7957,
      "longitude": 86.4304,
      "inspectionType": "Safety",
      "correctiveAction": "Address: Roof instability detected in gallery G-4",
      "deadline": 1209600000,
      "createdAt": -1209600000
    },
    {
      "severity": "HIGH",
      "description": "Methane concentration above safe limits",
      "observations": "CH4 readings at 2.1% in east gallery \u2014 above 1.5% threshold.",
      "status": "OPEN",
      "_id": "inspection-10",
      "mineId": "mine-6",
      "inspectorId": "inspector-5",
      "inspectorName": "Vikram Patel",
      "date": -1036800000,
      "latitude": 23.7957,
      "longitude": 86.4304,
      "inspectionType": "Environment",
      "correctiveAction": "Address: Methane concentration above safe limits",
      "deadline": 1209600000,
      "createdAt": -1036800000
    },
    {
      "severity": "LOW",
      "description": "Quarterly compliance review",
      "observations": "All major systems operational. Minor documentation gaps identified.",
      "status": "RESOLVED",
      "_id": "inspection-11",
      "mineId": "mine-7",
      "inspectorId": "inspector-1",
      "inspectorName": "Rajesh Kumar",
      "date": -864000000,
      "latitude": 18.8679,
      "longitude": 79.4612,
      "inspectionType": "General Compliance",
      "correctiveAction": null,
      "deadline": null,
      "createdAt": -864000000
    },
    {
      "severity": "HIGH",
      "description": "Support pillar deterioration",
      "observations": "3 support pillars showing signs of stress. Engineering assessment needed.",
      "status": "OPEN",
      "_id": "inspection-12",
      "mineId": "mine-10",
      "inspectorId": "inspector-2",
      "inspectorName": "Priya Sharma",
      "date": -691200000,
      "latitude": 21.8958,
      "longitude": 83.3963,
      "inspectionType": "Safety",
      "correctiveAction": "Address: Support pillar deterioration",
      "deadline": 1209600000,
      "createdAt": -691200000
    },
    {
      "severity": "MEDIUM",
      "description": "Conveyor belt wear assessment",
      "observations": "Belt segment 4 showing excessive wear. Replacement recommended within 30 days.",
      "status": "IN_PROGRESS",
      "_id": "inspection-13",
      "mineId": "mine-11",
      "inspectorId": "inspector-3",
      "inspectorName": "Amit Singh",
      "date": -518400000,
      "latitude": 23.6667,
      "longitude": 85.3667,
      "inspectionType": "Equipment",
      "correctiveAction": "Address: Conveyor belt wear assessment",
      "deadline": 1209600000,
      "createdAt": -518400000
    },
    {
      "severity": "MEDIUM",
      "description": "Shift handover protocol review",
      "observations": "Handover documentation incomplete in 40% of cases.",
      "status": "IN_PROGRESS",
      "_id": "inspection-14",
      "mineId": "mine-1",
      "inspectorId": "inspector-4",
      "inspectorName": "Sunita Devi",
      "date": -345600000,
      "latitude": 23.7509,
      "longitude": 86.4148,
      "inspectionType": "Labour",
      "correctiveAction": "Address: Shift handover protocol review",
      "deadline": 1209600000,
      "createdAt": -345600000
    },
    {
      "severity": "LOW",
      "description": "Green belt plantation status check",
      "observations": "85% sapling survival rate. Healthy growth observed.",
      "status": "RESOLVED",
      "_id": "inspection-15",
      "mineId": "mine-4",
      "inspectorId": "inspector-5",
      "inspectorName": "Vikram Patel",
      "date": -172800000,
      "latitude": 20.9517,
      "longitude": 85.2336,
      "inspectionType": "Environment",
      "correctiveAction": null,
      "deadline": null,
      "createdAt": -172800000
    }
  ],
  "violations": [
    {
      "category": "Safety",
      "description": "Blocked emergency evacuation route \u2014 workers at risk",
      "severity": "CRITICAL",
      "status": "OPEN",
      "deadline": -18307200000,
      "_id": "violation-1",
      "mineId": "mine-1",
      "violationId": "VIO-0001",
      "reportedBy": "Rajesh Kumar",
      "date": -4665600000,
      "correctiveAction": "Address violation: Blocked emergency evacuation route \u2014 workers at risk",
      "assignedPerson": "Priya Sharma",
      "resolutionDate": null,
      "createdAt": -4665600000
    },
    {
      "category": "Safety",
      "description": "Non-functional gas monitoring system in main shaft",
      "severity": "HIGH",
      "status": "IN_PROGRESS",
      "deadline": -17788800000,
      "_id": "violation-2",
      "mineId": "mine-1",
      "violationId": "VIO-0002",
      "reportedBy": "Priya Sharma",
      "date": -4406400000,
      "correctiveAction": "Address violation: Non-functional gas monitoring system in main shaft",
      "assignedPerson": "Amit Singh",
      "resolutionDate": null,
      "createdAt": -4406400000
    },
    {
      "category": "Environment",
      "description": "Illegal water discharge into watercourse",
      "severity": "HIGH",
      "status": "OPEN",
      "deadline": -17961600000,
      "_id": "violation-3",
      "mineId": "mine-1",
      "violationId": "VIO-0003",
      "reportedBy": "Amit Singh",
      "date": -4147200000,
      "correctiveAction": "Address violation: Illegal water discharge into watercourse",
      "assignedPerson": "Sunita Devi",
      "resolutionDate": null,
      "createdAt": -4147200000
    },
    {
      "category": "Safety",
      "description": "Recurring PPE non-compliance in sector 2",
      "severity": "MEDIUM",
      "status": "OPEN",
      "deadline": -17616000000,
      "_id": "violation-4",
      "mineId": "mine-1",
      "violationId": "VIO-0004",
      "reportedBy": "Sunita Devi",
      "date": -3888000000,
      "correctiveAction": "Address violation: Recurring PPE non-compliance in sector 2",
      "assignedPerson": "Vikram Patel",
      "resolutionDate": null,
      "createdAt": -3888000000
    },
    {
      "category": "Labour",
      "description": "Incomplete shift handover documentation",
      "severity": "MEDIUM",
      "status": "IN_PROGRESS",
      "deadline": -17356800000,
      "_id": "violation-5",
      "mineId": "mine-1",
      "violationId": "VIO-0005",
      "reportedBy": "Vikram Patel",
      "date": -3628800000,
      "correctiveAction": "Address violation: Incomplete shift handover documentation",
      "assignedPerson": "Rajesh Kumar",
      "resolutionDate": null,
      "createdAt": -3628800000
    },
    {
      "category": "Environment",
      "description": "PM2.5 levels exceeding permissible limits",
      "severity": "HIGH",
      "status": "OPEN",
      "deadline": -18048000000,
      "_id": "violation-6",
      "mineId": "mine-2",
      "violationId": "VIO-0006",
      "reportedBy": "Rajesh Kumar",
      "date": -3369600000,
      "correctiveAction": "Address violation: PM2.5 levels exceeding permissible limits",
      "assignedPerson": "Priya Sharma",
      "resolutionDate": null,
      "createdAt": -3369600000
    },
    {
      "category": "Safety",
      "description": "Inadequate lighting in underground sections",
      "severity": "MEDIUM",
      "status": "IN_PROGRESS",
      "deadline": -17788800000,
      "_id": "violation-7",
      "mineId": "mine-2",
      "violationId": "VIO-0007",
      "reportedBy": "Priya Sharma",
      "date": -3110400000,
      "correctiveAction": "Address violation: Inadequate lighting in underground sections",
      "assignedPerson": "Amit Singh",
      "resolutionDate": null,
      "createdAt": -3110400000
    },
    {
      "category": "Safety",
      "description": "Recurring dust control failures",
      "severity": "HIGH",
      "status": "OPEN",
      "deadline": -18134400000,
      "_id": "violation-8",
      "mineId": "mine-2",
      "violationId": "VIO-0008",
      "reportedBy": "Amit Singh",
      "date": -2851200000,
      "correctiveAction": "Address violation: Recurring dust control failures",
      "assignedPerson": "Sunita Devi",
      "resolutionDate": null,
      "createdAt": -2851200000
    },
    {
      "category": "Equipment",
      "description": "Overdue brake inspection on haul trucks",
      "severity": "MEDIUM",
      "status": "IN_PROGRESS",
      "deadline": -17529600000,
      "_id": "violation-9",
      "mineId": "mine-3",
      "violationId": "VIO-0009",
      "reportedBy": "Sunita Devi",
      "date": -2592000000,
      "correctiveAction": "Address violation: Overdue brake inspection on haul trucks",
      "assignedPerson": "Vikram Patel",
      "resolutionDate": null,
      "createdAt": -2592000000
    },
    {
      "category": "Environment",
      "description": "Ground water contamination risk",
      "severity": "HIGH",
      "status": "OPEN",
      "deadline": -17961600000,
      "_id": "violation-10",
      "mineId": "mine-3",
      "violationId": "VIO-0010",
      "reportedBy": "Vikram Patel",
      "date": -2332800000,
      "correctiveAction": "Address violation: Ground water contamination risk",
      "assignedPerson": "Rajesh Kumar",
      "resolutionDate": null,
      "createdAt": -2332800000
    },
    {
      "category": "Safety",
      "description": "Roof instability in gallery G-4",
      "severity": "CRITICAL",
      "status": "ESCALATED",
      "deadline": -18393600000,
      "_id": "violation-11",
      "mineId": "mine-6",
      "violationId": "VIO-0011",
      "reportedBy": "Rajesh Kumar",
      "date": -2073600000,
      "correctiveAction": "Address violation: Roof instability in gallery G-4",
      "assignedPerson": "Priya Sharma",
      "resolutionDate": null,
      "createdAt": -2073600000
    },
    {
      "category": "Safety",
      "description": "Methane levels above safety threshold",
      "severity": "CRITICAL",
      "status": "ESCALATED",
      "deadline": -18307200000,
      "_id": "violation-12",
      "mineId": "mine-6",
      "violationId": "VIO-0012",
      "reportedBy": "Priya Sharma",
      "date": -1814400000,
      "correctiveAction": "Address violation: Methane levels above safety threshold",
      "assignedPerson": "Amit Singh",
      "resolutionDate": null,
      "createdAt": -1814400000
    },
    {
      "category": "Labour",
      "description": "Safety certification lapsed for contractors",
      "severity": "HIGH",
      "status": "OPEN",
      "deadline": -17875200000,
      "_id": "violation-13",
      "mineId": "mine-6",
      "violationId": "VIO-0013",
      "reportedBy": "Amit Singh",
      "date": -1555200000,
      "correctiveAction": "Address violation: Safety certification lapsed for contractors",
      "assignedPerson": "Sunita Devi",
      "resolutionDate": null,
      "createdAt": -1555200000
    },
    {
      "category": "Safety",
      "description": "Support pillar deterioration requiring engineering review",
      "severity": "HIGH",
      "status": "OPEN",
      "deadline": -17702400000,
      "_id": "violation-14",
      "mineId": "mine-10",
      "violationId": "VIO-0014",
      "reportedBy": "Sunita Devi",
      "date": -1296000000,
      "correctiveAction": "Address violation: Support pillar deterioration requiring engineering review",
      "assignedPerson": "Vikram Patel",
      "resolutionDate": null,
      "createdAt": -1296000000
    },
    {
      "category": "Safety",
      "description": "Recurring ventilation issues in deep gallery",
      "severity": "MEDIUM",
      "status": "OPEN",
      "deadline": -17356800000,
      "_id": "violation-15",
      "mineId": "mine-10",
      "violationId": "VIO-0015",
      "reportedBy": "Vikram Patel",
      "date": -1036800000,
      "correctiveAction": "Address violation: Recurring ventilation issues in deep gallery",
      "assignedPerson": "Rajesh Kumar",
      "resolutionDate": null,
      "createdAt": -1036800000
    },
    {
      "category": "Equipment",
      "description": "Conveyor belt wear exceeding safe limits",
      "severity": "MEDIUM",
      "status": "IN_PROGRESS",
      "deadline": -17184000000,
      "_id": "violation-16",
      "mineId": "mine-11",
      "violationId": "VIO-0016",
      "reportedBy": "Rajesh Kumar",
      "date": -777600000,
      "correctiveAction": "Address violation: Conveyor belt wear exceeding safe limits",
      "assignedPerson": "Priya Sharma",
      "resolutionDate": null,
      "createdAt": -777600000
    },
    {
      "category": "Safety",
      "description": "Emergency response plan outdated",
      "severity": "CRITICAL",
      "status": "OPEN",
      "deadline": -18048000000,
      "_id": "violation-17",
      "mineId": "mine-11",
      "violationId": "VIO-0017",
      "reportedBy": "Priya Sharma",
      "date": -518400000,
      "correctiveAction": "Address violation: Emergency response plan outdated",
      "assignedPerson": "Amit Singh",
      "resolutionDate": null,
      "createdAt": -518400000
    },
    {
      "category": "Production",
      "description": "Coal quality deviation from standards",
      "severity": "LOW",
      "status": "RESOLVED",
      "deadline": -18652800000,
      "_id": "violation-18",
      "mineId": "mine-4",
      "violationId": "VIO-0018",
      "reportedBy": "Amit Singh",
      "date": -259200000,
      "correctiveAction": "Address violation: Coal quality deviation from standards",
      "assignedPerson": "Sunita Devi",
      "resolutionDate": -172800000,
      "createdAt": -259200000
    }
  ],
  "contractors": [
    {
      "name": "Bharat Mining Services",
      "contactPerson": "Suresh Patel",
      "serviceType": "Drilling & Excavation",
      "riskScore": 75,
      "violations": 3,
      "pendingActions": 2,
      "_id": "contractor-1",
      "mineId": "mine-1",
      "phone": "+91-9000000001",
      "email": "suresh.patel@example.com",
      "status": "UNDER_REVIEW",
      "createdAt": -5184000000
    },
    {
      "name": "SafeGuard Safety Solutions",
      "contactPerson": "Meera Iyer",
      "serviceType": "Safety Equipment Supply",
      "riskScore": 30,
      "violations": 0,
      "pendingActions": 0,
      "_id": "contractor-2",
      "mineId": "mine-1",
      "phone": "+91-9000000002",
      "email": "meera.iyer@example.com",
      "status": "ACTIVE",
      "createdAt": -5184000000
    },
    {
      "name": "Eastern Earth Movers",
      "contactPerson": "Ravi Shankar",
      "serviceType": "Heavy Equipment",
      "riskScore": 65,
      "violations": 2,
      "pendingActions": 1,
      "_id": "contractor-3",
      "mineId": "mine-2",
      "phone": "+91-9000000003",
      "email": "ravi.shankar@example.com",
      "status": "ACTIVE",
      "createdAt": -5184000000
    },
    {
      "name": "Central Logistics Corp",
      "contactPerson": "Arun Mehta",
      "serviceType": "Transportation",
      "riskScore": 45,
      "violations": 1,
      "pendingActions": 0,
      "_id": "contractor-4",
      "mineId": "mine-3",
      "phone": "+91-9000000004",
      "email": "arun.mehta@example.com",
      "status": "ACTIVE",
      "createdAt": -5184000000
    },
    {
      "name": "Deep Shaft Engineering",
      "contactPerson": "Karan Bhat",
      "serviceType": "Underground Construction",
      "riskScore": 82,
      "violations": 4,
      "pendingActions": 3,
      "_id": "contractor-5",
      "mineId": "mine-6",
      "phone": "+91-9000000005",
      "email": "karan.bhat@example.com",
      "status": "UNDER_REVIEW",
      "createdAt": -5184000000
    },
    {
      "name": "Green Environmental Services",
      "contactPerson": "Nisha Gupta",
      "serviceType": "Environmental Monitoring",
      "riskScore": 25,
      "violations": 0,
      "pendingActions": 0,
      "_id": "contractor-6",
      "mineId": "mine-4",
      "phone": "+91-9000000006",
      "email": "nisha.gupta@example.com",
      "status": "ACTIVE",
      "createdAt": -5184000000
    },
    {
      "name": "Raigarh Mining Solutions",
      "contactPerson": "Devendra Rai",
      "serviceType": "Roof Support & Bolting",
      "riskScore": 58,
      "violations": 2,
      "pendingActions": 1,
      "_id": "contractor-7",
      "mineId": "mine-10",
      "phone": "+91-9000000007",
      "email": "devendra.rai@example.com",
      "status": "ACTIVE",
      "createdAt": -5184000000
    },
    {
      "name": "Ramgarh Equipment Services",
      "contactPerson": "Manoj Kumar",
      "serviceType": "Equipment Maintenance",
      "riskScore": 40,
      "violations": 1,
      "pendingActions": 0,
      "_id": "contractor-8",
      "mineId": "mine-11",
      "phone": "+91-9000000008",
      "email": "manoj.kumar@example.com",
      "status": "ACTIVE",
      "createdAt": -5184000000
    }
  ],
  "alerts": [
    {
      "title": "Critical: Gas Monitor Failure",
      "message": "Mine A \u2014 3 gas detectors non-functional in main shaft. Immediate action required.",
      "type": "CRITICAL_VIOLATION",
      "severity": "CRITICAL",
      "_id": "alert-1",
      "mineId": "mine-1",
      "userId": "all",
      "read": false,
      "createdAt": 0
    },
    {
      "title": "Overdue: Evacuation Route Blockage",
      "message": "Mine A \u2014 Emergency route B-7 blocked. Deadline passed 1 day ago.",
      "type": "OVERDUE_COMPLIANCE",
      "severity": "CRITICAL",
      "_id": "alert-2",
      "mineId": "mine-1",
      "userId": "all",
      "read": false,
      "createdAt": -86400000
    },
    {
      "title": "Escalated: Roof Instability",
      "message": "Mine F \u2014 Gallery G-4 showing signs of structural failure. Escalated to management.",
      "type": "ESCALATED_ACTION",
      "severity": "CRITICAL",
      "_id": "alert-3",
      "mineId": "mine-6",
      "userId": "all",
      "read": false,
      "createdAt": -172800000
    },
    {
      "title": "High Risk: Methane Levels",
      "message": "Mine F \u2014 CH4 at 2.1% exceeds 1.5% safety threshold.",
      "type": "CRITICAL_VIOLATION",
      "severity": "CRITICAL",
      "_id": "alert-4",
      "mineId": "mine-6",
      "userId": "all",
      "read": false,
      "createdAt": -259200000
    },
    {
      "title": "Overdue: Environmental Report",
      "message": "Mine C \u2014 Ground water monitoring report overdue by 4 days.",
      "type": "OVERDUE_COMPLIANCE",
      "severity": "HIGH",
      "_id": "alert-5",
      "mineId": "mine-3",
      "userId": "all",
      "read": false,
      "createdAt": -345600000
    },
    {
      "title": "Risk Increase: Mine A",
      "message": "Mine A risk score increased from 79 to 87 in the last reporting period.",
      "type": "RISK_INCREASE",
      "severity": "HIGH",
      "_id": "alert-6",
      "mineId": "mine-1",
      "userId": "all",
      "read": false,
      "createdAt": -432000000
    },
    {
      "title": "Upcoming: License Renewal",
      "message": "Mine A \u2014 Annual mining license renewal due in 15 days.",
      "type": "UPCOMING_DEADLINE",
      "severity": "MEDIUM",
      "_id": "alert-7",
      "mineId": "mine-1",
      "userId": "all",
      "read": false,
      "createdAt": -518400000
    },
    {
      "title": "Compliance Alert: Dust Levels",
      "message": "Mine B \u2014 PM2.5 at 180 \u00b5g/m\u00b3 exceeds limits. Dust suppression required.",
      "type": "CRITICAL_VIOLATION",
      "severity": "HIGH",
      "_id": "alert-8",
      "mineId": "mine-2",
      "userId": "all",
      "read": false,
      "createdAt": -604800000
    },
    {
      "title": "Overdue: Roof Support",
      "message": "Mine F \u2014 Roof support reinforcement overdue by 6 days.",
      "type": "OVERDUE_COMPLIANCE",
      "severity": "HIGH",
      "_id": "alert-9",
      "mineId": "mine-6",
      "userId": "all",
      "read": false,
      "createdAt": -691200000
    },
    {
      "title": "Upcoming: Safety Drill",
      "message": "Mine B \u2014 Contractor safety audit due in 8 days.",
      "type": "UPCOMING_DEADLINE",
      "severity": "MEDIUM",
      "_id": "alert-10",
      "mineId": "mine-2",
      "userId": "all",
      "read": false,
      "createdAt": -777600000
    }
  ]
} as const;
